---
version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    restart: always
  app:
    build:
      context: .
    command: flask run -h 0.0.0.0
    environment:
      FLASK_ENV: development
      DEBUG: 1
      DATABASE_URL: postgresql://postgres:postgres@db:5432/database
    volumes:
      - .:/home/bootstrapper
    depends_on:
      - db
    restart: always
  proxy:
    build:
      context: ./services/proxy
    ports:
      - 8080:80
    depends_on:
      - app
    restart: always
