---
version: "3.3"
services:
  db:
    image: ${DB_IMAGE}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DEFAULT_DATABASE}
    restart: always
  app:
    build:
      context: .
    command: ${APP_BOOTSTRAP_COMMAND}
    environment:
      FLASK_ENV: development
      DEBUG: 1
      DATABASE_URL: ${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DEFAULT_DATABASE}
    volumes:
      - .:/home/bootstrapper
    depends_on:
      - db
    restart: always
  proxy:
    build:
      context: ./services/proxy
    ports:
      - ${PROXY_HOST_PORT}:80
    depends_on:
      - app
    restart: always
